### ISSUE TITLE
How to remove sender permanently ?

### ISSUE THREAD

**Issue by developper89** [mailjet/mailjet-apiv3-php#136]
When trying to add a deleted sender i get a 400 error saying: "There is an already existing deleted sender with the same email."
Is it possible to remove a sender permanently  ?

**Comment by kmanchikov** [comment]
Hey there, 

Would you like to permanently delete the Sender or reactivate it ? I am asking that questions since you have tried to re-add the sender, thus you would most probably want to re-use it again. 

Because if that is the case, then you just need to validate again the deleted sender, in order for it to be reactivated. 

Best, 
Krassimir
