### ISSUE TITLE
InlinedAttachments not displayed in Thunderbird Send API v3.1

### ISSUE THREAD

**Issue by LrntL** [mailjet/mailjet-apiv3-php#163]
Hi,

Not sure about this, but it seems that inlined attachments are not displayed in Thunderbird (v.60.5.0). They are just listed as simple attachments.

Here is my code:

```
use \Mailjet\Resources;
$mj = new \Mailjet\Client("APIKEY_PUBLIC", "APIKEY_PRIVATE",true,['version' => 'v3.1']);
$body = [
    'Messages' => [
        [
            'From' => [
                'Email' => "contact@domain.com",
                'Name' => "Sender"
            ],
            'To' => [
                [
                    'Email' => "someone@somedomain.com", 
                    'Name' => "Someone"
                ]
            ],
            'Subject' => "Your email flight plan!",
            'TextPart' => "Dear passenger 1, welcome to Mailjet! May the delivery force be with you!",
            'HTMLPart' => "<h3>Dear passenger 1, welcome to <img src=\"cid:my_picture.png\"> Mailjet!</h3><br />May the delivery force be with you!",
            'InlinedAttachments' => [
                [
                    'ContentType' => "image/png",
                    'Filename' => "my_picture.png",
                    'ContentID' => "my_picture.png",
                    'Base64Content' => base64_encode(file_get_contents("path_to_my_picture/my_picture.png"))
                ]
            ]
        ]
    ]
];
$response = $mj->post(Resources::$Email, ['body' => $body]);
$response->success() && var_dump($response->getData());
```

I heard that it is a known bug...
Is there a way to fix this ?

Thanks.

**Comment by adamyanliev** [comment]
hey @LrntL ,

basically it boils down to the way Thunderbird is interpreting the content of the email. All major email clients interpret the content with attached files sent by Mailjet as `multipart/related`, which allows for the attachment to be added to the HTML part. Thunderbird, however, interprets it as `multipart/mixed`, so it cannot add the attachment inline. This is a known problem with Thunderbird, but unfortunately at the moment there is no possibility to override this manually.

You could add the encoded message definition directly into the <img> tag, e.g. `<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAFCAIAAADtz9qMAAAAEElEQVQImWOwD+6DIwYyOADVcxaBMyMVNwAAAABJRU5ErkJggg==">` . This way it will be recognized by Thunderbird, but will probably bring up issues with other clients - not to mention that it's quite inconvenient.

One last small note - I imagine that it was because of copy/pasting, but in your code sample you are referring to the content ID as `my_picture.png`, when a bit lower you've defined it as `id1`. when setting a value for the cid, you should use the ContentID value you have set.

Regards,
Atanas

**Comment by LrntL** [comment]
Thanks !

It's too bad that a solution can not be found with Thunderbird. By the way, thank you for last small note ;) I updated my first post.

I really don't want to switch back to phpMailer to prepare the content with  which it works :/

**Comment by adamyanliev** [comment]
Hi,

Yes, adding a URL should work without any issues, as Thunderbird (as well as any other mail client) will correctly interpret the HTML.

**Comment by LrntL** [comment]
Yes, I think it is the "best" choice.
Thank you for helping and explanations.
I close this ;)

**Comment by calldeludo** [comment]
I am trying to print an image in my email, i am passing it as a HTMLPart in base64 code... but is not working

this is my code 

```
   const request = mailjet.post("send", { 'version': 'v3.1' }).request({
        "Messages": [
            {
                "From": {
                    "Email": `${req.body.remitente}`,
                    "Name": `${req.body.nombreRemitente}`
                },
                "To": destinatarios,
                "Subject": `${req.body.asunto}`,
                "HTMLPart": `<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAFCAIAAADtz9qMAAAAEElEQVQImWOwD+6DIwYyOADVcxaBMyMVNwAAAABJRU5ErkJggg==">`,
                "CustomID": "AppGettingStartedTest",
                "Headers": { "Reply-To": `${req.body.replyEmail}` },
                "Attachments": [
                    {
                        "ContentType": "application/pdf",
                        "Filename": `${req.body.fileName}.pdf`,
                        "Base64Content": `${req.body.adjunto[1]}`
                    }
                ]
            }
        ]
    })
    request.then((result) => {
        res.json(result)
    }).catch((err) => {
        res.json(err)
    })
```
what am i doing wrong?
