### ISSUE TITLE
PHP 5.6 - 'Fatal error: class Throwable not found.'

### ISSUE THREAD

**Issue by moooss** [mailjet/mailjet-apiv3-php#186]
Hi,

I'm working on a project using PHP 5.6, I installed the code and dependencies with composer.
Everything is working fine but one (big) detail, when something isn't working properly, I'm having the message below :

`Fatal error</b>:  Uncaught exception 'Exception' with message 'Fatal error: class Throwable not found.'`

So I don't see any error message.

The error comes from guzzle.
As far as I understand it, guzzle error management works with "Throwable", which is a PHP 7 feature...

I tried to add a version parameter in composer.json but it didn't change anything.

`  "config": {
    "platform": {
        "php": "5.6.4"
    }
  },`

It seems to me that the compatibility is not ok with PHP < 7.
Any idea of what I could try next ?

**Comment by btronquo** [comment]
Hi, 

I had the same problem with guzzle until I ran a clean install from scratch.

If you want, you can use my repo (no need to have composer) and test.

I tested it in PHP 5.6 / 7.2 / 7.3 / 7.4 and it works ;)

**Comment by mathieumousse** [comment]
That's nice thank you.
I'll give it a try

**Comment by moooss** [comment]
Hi,
Same same here.
I finally gave it a try, and it gives the same result :/
It's coming from something else.

Thank you anyway !

**Comment by uavn** [comment]
@moooss Is this issue still valid for you?

Because Throwable is PHP 7+ feature, which is not available in PHP 5.6, it is used in Guzzle v7 package, which is dependency for mailjet, but when you are doing fresh install from machine with php 5.6 it will install old Guzzle of v.6 without Throwable and with PHP 5.6 support, but if you install dependencies from machine with php 7 and then use on machine with 5.6 - it will give you that error, otherwise - it should work.

Here is mailjet with its dependencies for PHP 5.6 that works for me - https://drive.google.com/file/d/1vm2VTefCS8lI-HI6eDxg04AM-0bicGcD/view?usp=sharing
