### ISSUE TITLE
How can i get  only the contacts who are unsubscribed from a contact list ? 

### ISSUE THREAD

**Issue by Modjo69** [mailjet/mailjet-apiv3-php#209]

**Comment by uavn** [comment]
@Modjo69 You can't.

You can get a list of contacts from a contact list:
```
$mj = new \Mailjet\Client($key, $secret, true, ['version' => 'v3']);

$response = $mj->get(Resources::$Contact, [
    'filters' => [
        'ContactsList' => 41819
    ],
]);
```

and due to documentation (https://dev.mailjet.com/email/reference/contacts/contact#v3_get_contact), there is a property UnsubscribedAt, but it is marked as deprecated, and for me it returns nothing, even if I unsubscribed my contact from the list.

The only thing I found - you can get contact statistics by this endpoint - https://dev.mailjet.com/email/reference/statistics#v3_get_contactstatistics_contact_ID
and there is a field, called 'UnsubscribedCount', which is not deprecated and works as expected, this will not give you anything about lists from which this used unsubscribed, but if your contact is unique for single list, you can try to get contacts ID from your list, by first endpoint, then you can get statistics for that user and check if it has UnsubscribedCount > 0, but, again, this is not accurate, because if user is in two or more lists - you'll not be able to know, from which list user was unsubscribed.

Something like this:
```
$mj = new \Mailjet\Client($key, $secret, true, ['version' => 'v3']);

$response = $mj->get(Resources::$Contact, [
    'filters' => [
        'ContactsList' => 41819
    ],
]);

$unsubscribedContacts = [];

foreach ($response->getData() as $datum) {
    $contactId = $datum['ID'];

    $response = $mj->get(Resources::$Contactstatistics, [
        'id' => $contactId,
    ]);

    if ($response->getData()[0]['UnsubscribedCount']) {
        $unsubscribedContacts[] = $datum;
    }
}


print_r($unsubscribedContacts);
die;
```

**Comment by Modjo69** [comment]
hello, finally i find a way :  

$mj = new \Mailjet\Client($cle_api, $cle_api_secret,true,['version' => 'v3']);
$var=1000;
$count=0;
// i past in all my users
for ( $d=0 ; $d<32000 ; $d+=$var ){	
	$offset+=$d;
	$limit=$var;
	$filters = [
		'IsExcludedFromCampaigns' => false,
		'Offset'=>$offset,
		'Limit'=>$limit,		
	];
	$response = $mj->get(Resources::$Contact, ['filters' => $filters]);
	$response->success() ;
	$response=$response->getData();

// i loop on all my usersid in "$ContactGetcontactslists" and use the param isUnsub from each list where the contact is present

	foreach($response as $i){
		$id=$i["ID"];
		$responseBit = $mj->get(Resources::$ContactGetcontactslists, ['id'=> $id]);
		$responseBit->success() ;
		$responseBit=$responseBit->getData();
		foreach($responseBit as $j){
			if($j["IsUnsub"]==true){ 
				echo "mail: ".$i["Email"] ." - list unsub id : ". $j["ListID"]."<br>";
			}	
		}
				
	}
}
