### ISSUE TITLE
Unsubscriptions not detected

### ISSUE THREAD

**Issue by Pythorogus** [mailjet/mailjet-apiv3-php#54]
Hi,
I've got a problem with subscribes and contacts lists : i unsubscribed 2 mail on a contact list. Then I sent a request to get the subscribed mail of this list. But apparently, it always returns all the list.
All "UnsubscribedAt" properties of the contacts are empty.
I checked, the mails are unsubscribed, on the mailjet site.
My request : 
$filters = ['ContactsList' => "1",'IsUnsubscribed' => false];
$response = $mj->get(Resources::$Contact,['filters'=>$filters]);

If 'IsUnsubscribed'  = false => Returns me the contact list 1.
If 'IsUnsubscribed'  = true => Returns me empty array.
In fact, it seems not detect if a contact is unsubscribed (instead the unsubscriptions marked in the contact list, on the mailjet site).
I tested with exclusions, and it works for it. But I don't understand why it doesn't with subscriptions.
Api problem, or of mine ?

**Comment by GuillaumeBadi** [comment]
Hey ! Sorry for the delay. At the moment, the only way to achieve this is to trigger a call on listrecients:  http://dev.mailjet.com/email-api/v3/listrecipient/ , to get the unsubscribed contacts IDs, then call /contact with each ID

Let me know if it works for you!

Guillaume

**Comment by Pythorogus** [comment]
It worked, thank you !

**Comment by kutsyk** [comment]
Any updates on this? Started `isUnsubscribed` filter working?

**Comment by adamyanliev** [comment]
Hey @kutsyk ,

the `UnsubscribedAt` / `UnsubscribedBy` properties for `contact` were deprecated some time ago, so the `IsUnsubscribed` filter is deprecated as well. We're working on updating the API reference to match this change and some others.

As mentioned Guillaume's comment, please use the [`/listrecipient`](https://dev.mailjet.com/email-api/v3/listrecipient/) resource instead.

**Comment by nadar** [comment]
We really need a filter for this - are there any news on this? /listrecipient with call for every contact is really not a good solution for huge contactlist - also for mailjet infrastructure.

**Comment by nadar** [comment]
@adamyanliev also https://dev.mailjet.com/reference/email/contacts/contact/#v3_get_contact is talking about a "status" filter with a string value .. its not documented what this should be? should i create a new issue about that?

**Comment by adamyanliev** [comment]
Hey @nadar , unfortunately due to the current structure of the API there's no way to retrieve the emails of all unsubscribed contacts from a list in a single call. Basically the unsubscription status is saved in `listrecipient` objects, since they provide the link between contacts and the lists they're subscribed to. And the emails are kept in the `contact` objects linked to those list recipients. 

There's a plan to revamp and simplify the different API endpoints, but it's a huge project and will take quite a while before it's ready.

Meanwhile, you can retrieve the IDs of all contacts unsubscribed from a certain list with the `/listrecipient` endpoint by using the `ContactsList` and `Unsub` filters together, but will need to do separate calls for each contact ID to get the email.

A different option you might consider is using our Event API to track unsubscription events and send a summary of those to a URL of your choice. The event information includes the email of the user who triggered it, so this will probably be more convenient. See the [Event API](https://dev.mailjet.com/guides/#endpoint-url) section of our guide for more info.

about the `Status` filter - this is a deprecated one that slipped through and was left in the updated version of the reference. There's no need for another issue, we'll delete it with the next update. Apologies for the confusion.

**Comment by nadar** [comment]
We have setup a Hook (trigger => https://app.mailjet.com/account/triggers) for the unsub event, the problem is the Event API does not call the url when clicking unsubscribe button in the mailjet UI. (and yes the test payload works perfectly and our system writes every request into a log).

This button i mean: 
![image](https://user-images.githubusercontent.com/3417221/51916267-42626500-23dd-11e9-8ccf-210b6e93bc40.png)
(yes the unsubscribe button is hidden because the screenshot tool under ubuntu is unable to handle the mouse over event :smile: - but i assume you know which UI i mean)

**Comment by nadar** [comment]
@adamyanliev I also wrote the mailjet support team - but this usual takes weeks and secondly they do not have a technical know-how so all they response is "can i have the api key", "are you triggering the things right", "what is the response" .. sadly we have so many issues on a technical level which makes it a pain to integrate mailjet nicely (also about blocked senders from unknown reason and error handling does not send mails to error mail) - we really try to do a very easy to use library for Yii Framework and LUYA developers: https://github.com/luyadev/luya-mailjet

Thanks for helping us @adamyanliev

**Comment by adamyanliev** [comment]
hey @nadar , yeah, the Event API cannot track manual unsubscriptions from the app. 

We'll work on updating the API, but as I mentioned, it's going to take time. Hopefully adding an easy way to find contact emails by unsub status will be higher on the priority list.
