### ISSUE TITLE
Mailjet Response is Empty

### ISSUE THREAD

**Issue by Amina24** [mailjet/mailjet-apiv3-php#80]
Using Mailjet API key for sending email. I am sending bulk and individual email. 
Some time Mailjet response is empty, I want to know why response of Mailjet is empty. Is it normal behavior ? and What are the conditions at which Mailjet send empty response. 
Note : Most of the time email sending properly. We are facing this problem almost  last 3 days. Do we have any API issue or anything?? please reply soon.
Thank you

**Comment by Zhivko-Mailjet** [comment]
@Amina24 
Normally, we should not send empty responses. We will have to look deeper here into your account. Please open a [support ticket](https://www.mailjet.com/support/ticket), selecting the API category and provide:
- API key
- API call
- API response returned
- Any additional information

You can reference the Github link in the ticket.

**Comment by Zhivko-Mailjet** [comment]
The problem was related to a property value null sent to our SendAPI. When this happens, we generate specific error message (500 Cannot convert data from Null value") and do not fail silently.

You can NOT do:
'Property' => null

What you can do instead:
'Property' => ""
OR
'Property' => "null"

The issue was has been resolved after contacting the support team.

**Comment by sagarmumbaidev** [comment]
How can we check the **NULL** value in mailjet template?
